import '@/styles/global.css';

import { ReactNode } from 'react';
import { Inter } from 'next/font/google';

import { Providers } from '@/components/Providers';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hatenna",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-secondary-button text-primary antialiased`}
        suppressHydrationWarning={true}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
